module Main (main) where

import Control.Exception
import System.Environment
import System.Exit
import System.Process
import System.Random

getInsult :: ExitCode -> IO (String, ExitCode)
getInsult code@ExitSuccess = return ("", code)
getInsult code@(ExitFailure _) = do
    rnd <- randomRIO (0, length getAllInsults - 1)
    return (getAllInsults !! rnd, code)

performExecution :: String -> [String] -> IO ExitCode
performExecution cmd args = spawnProcess cmd args >>= waitForProcess

runWithArgs :: [String] -> IO (String, ExitCode)
runWithArgs [] = getInsult $ ExitFailure maxBound
runWithArgs (x:xs) = performExecution x xs >>= getInsult

main :: IO ()
main = do
    resultCode <- try (getArgs >>= runWithArgs) :: IO (Either SomeException (String, ExitCode))
    case resultCode of
        Right (_, ExitSuccess) -> return ()
        Right (msg, code@(ExitFailure _)) -> do
            putStrLn msg
            exitWith code

        Left err -> do
            print err
            (insult, code) <- getInsult $ ExitFailure maxBound
            putStrLn insult
            exitWith code


getAllInsults :: [String]
getAllInsults = ["Let me tell you. If I don’t answer you the first time, what makes you think the next 25 will work?",
                 "I told my therapist about you; she didn’t believe me.",
                 "Cry me a river, then drown yourself in it.",
                 "I don’t want to rain on your parade. I want a typhoon.",
                 "You have such a beautiful face… But let’s put a bag over that personality.",
                 "Every time I have a stick in my hand, you look like a pinata.",
                 "I don’t hate you, but if you were drowning, I would give you a high five.",
                 "What is wrong with you? Have you had too many drugs in mental hospital today?",
                 "You are what happens when women drink during pregnancy.",
                 "Hurting you is the least thing I want to do… but it’s still in the list.",
                 "I am not ignoring you; I am just giving you a time to understand what you just said.",
                 "Earth is full. Go home.",
                 "I like the way you comb your hair, so horns don’t show up.",
                 "I look at you and think what a waste of two billion years of the evolution.",
                 "When God made you, you must have been on the bottom of his “to-do” list.",
                 "You are the reason why God is not talking to us anymore.",
                 "God wanted to spice the earth with jokes, and he made your kind",
                 "It is better to shut your mouth and make people think you are stupid than open it and remove all doubt.",
                 "You hear that? It’s the sound of me not caring.",
                 "If I wanted to kill myself, I would simply jump from your ego to your IQ.",
                 "I am jealous of people who didn’t meet you.",
                 "Why are you rolling your eyes? Are you looking for your brain?",
                 "I’m sorry… did my back hurt your knife?",
                 "You’re not simply a drama queen. You’re the whole royal family.",
                 "I would call you an idiot, but it would be an insult for stupid people.",
                 "Only thing that is pleasing about our relationship is that you are no longer in it.",
                 "When I listen to you, I think you really going to go far. I hope you stay there.",
                 "Are you at a loss for words, or did you exhaust your entire vocabulary?",
                 "A glowstick has a brighter future than you. Lasts longer in bed, too.",
                 "Honey, only thing bothering me is placed between your ears.",
                 "Somewhere tree is producing oxygen for you. I’m sorry for it.",
                 "I know I make stupid choices, but you’re the worst of all my choices",
                 "You are the sun in my life… now get 93 million miles away from me.",
                 "I didn’t mean to offend you… but it was a huge plus.",
                 "Remember, if anyone says you’re beautiful, it’s all lies",
                 "You make me increase the amount of caffeine I take daily",
                 "You do realize we tolerate you.",
                 "It would be a great day If you used a glue stick instead of Chapstick.",
                 "You didn’t change since last time I saw you. You should.",
                 "You were so happy for the negativity of your Covid test, we didn’t want to spoil the happiness by telling you it was IQ test.",
                 "Everyone has purpose in this life, yours is to become an organ donor.",
                 "If I throw a stick, will you leave me too?",
                 "I’d tell you to blow your brains out, but I’m pretty certain there’s nothing there.",
                 "You are the reason why there are instructions on shampoo bottles.",
                 "When I look at you, I think to myself where have you been my whole life? Can you go back there?",
                 "I know you don’t like me, that says a lot. You need to acquire a better taste.",
                 "You are like a software update. every time I see you, I immediately think “not now”.",
                 "When I see you coming, I get pre annoyed. I’m just giving myself a head start.",
                 "Have a nice day… somewhere else.",
                 "I don’t know what makes you so stupid, but it works.",
                 "Whatever doesn’t kill you, disappoints me.",
                 "Are you talking to me? I thought you only talk behind my back.",
                 "Every time I think you can’t get any dumber, you are proving me wrong.",
                 "It is hilarious how you are trying to fit your entire vocabulary into one sentence.",
                 "Sorry I can’t think of an insult dumb enough for you to understand.",
                 "Taking a picture of you would put a virus on my phone",
                 "When I look at you, I wish I could meet you again for the first time… and walk past.",
                 "If I had a dollar every time you shut up, I would give it back as a thank you.",
                 "You can be anything you want…except good looking.",
                 "The good books say to make good friends, but I think I made a mistake",
                 "Did you know your incubator had tinted windows? That explains a lot.",
                 "I think you just need a high five… in the face… with a chair.",
                 "Where is your off button?",
                 "Everyone is allowed to act stupid once, but you… you are abusing that privilege.",
                 "The last time I saw something like you, it was behind metal grids.",
                 "Is part 2 of your argument coming out soon or is that it?",
                 "It’s all about balance… you start talking, I stop listening.",
                 "You deserve to be loved… from a distance",
                 "Ola soy Dora. Can you help me find where we asked?",
                 "I would smack you, but I’m against animal abuse.",
                 "Yes, I’m fully vaccinated, but I will still not hang out with you.",
                 "I can’t wait to spend my whole life without you.",
                 "You can’t imagine how much happiness you can bring… by leaving the room.",
                 "All mistakes are fixable, yet you aren’t.",
                 "There is someone out there for everyone. For you, it’s a therapist.",
                 "Oh, sorry, did the middle of my sentence interrupted the beginning of yours?",
                 "I gave out all my trophies a while ago, but here’s a participation award.",
                 "Whoever told you to be yourself, gave you a bad advice.",
                 "You’re the reason the divorce rate is so high.",
                 "I’ve never been a great cook, but I still know how to roast your ass.",
                 "I don’t want to rain on your parade. I want a typhoon.",
                 "I’ve never had many life goals. I’m just really grateful I’m not you.",
                 "The only person falling for you is blind.",
                 "Aww, don’t worry, you are wanted…wanted for several accounts of perjury.",
                 "I can’t think of anything to celebrate on your birthday except you being closer to death.",
                 "Don’t place your self-worth in other’s hands. That being said, allow me to redirect you to the discount section. I found a spot for you.",
                 "Has anyone ever tried to smack some sense into you? Allow me to be the first one.",
                 "I don’t have any trash to take out today, but I volunteer you as tribute.",
                 "The amount of meaningful things you’ve done in your life wouldn’t be enough to fill a single page.",
                 "I’d spell it out for you, but that’s assuming you know your ABC’s",
                 "You hit the nail right on the head. Too bad your parents took it literally.",
                 "I must have been imagining things. For a second there, I thought you made a valid point.",
                 "I’d have hired an exterminator if I knew you were gonna bug the shit out of me.",
                 "Louie Armstrong would have never released “What a Wonderful World” had he met you.",
                 "When God made you, you must have been on the bottom of his “to-do” list.",
                 "You’ve got something on your face. No, not there—everywhere.",
                 "No amount of self-editing can fix the massive failure your autobiography would be.",
                 "You should come with a warning label.",
                 "Your ignorance makes my racist uncle look like Albert Einstein.",
                 "They say our brains don’t stop developing until we reach 25; looks like yours stopped a bit early.",
                 "A balloon full of piss makes a bigger splash than your entire meaningless existence will on this planet.",
                 "You hear that? It’s the sound of me not caring.",
                 "No matter how many shmucks I meet in my life, I can always trust you to be the absolute worst.",
                 "You’re an unscented candle in a store full of beautiful fragrances.",
                 "How awful. I was just imagining the day of your birth in my head.",
                 "I didn’t put garlic over my door because I think you’re a vampire. It just smells much better than you.",
                 "I clean up germs all day, but no matter how hard I scrub, you’re still here.",
                 "Your skin is glowing, but I think it’s from the radiation emanating from your toxic ass personality.",
                 "You are the architect of your life. Unfortunately, the blueprints are messy, written in Mandarin, and waterlogged beyond all recognition. Good luck.",
                 "You’re not simply a drama queen. You’re the whole royal family.",
                 "Journey to the Center of the Earth was based on the quest to find where your head went after you shoved it up your own asshole.",
                 "Are you at a loss for words, or did you exhaust your entire vocabulary?",
                 "A glowstick has a brighter future than you. Lasts longer in bed, too.",
                 "Some people hatch into beautiful butterflies. Some people hatch into whatever the hell you are.",
                 "I wanted to live life without many regrets. Then I met you.",
                 "Listen to your doubts. I think they’re onto something.",
                 "There are so many paths in life. Why didn’t you choose the dark alleyway?",
                 "You’re lucky intelligence isn’t measured in negative numbers.",
                 "You seem to have a lot on your mind… a lot of bullshit.",
                 "Earth has a population of over 7 billion, and I had to meet the biggest loser imaginable.",
                 "I wrote something nice for you in invisible ink. Sorry, it must have washed off.",
                 "You must be magic because I suddenly don’t give a shit anymore!",
                 "Did God make you with his eyes closed?",
                 "I really enjoy the silence of your company. Can you stop talking more often?",
                 "My heart was beating fast when I saw you walk in. I thought you were the monster under my bed.",
                 "It takes me a lot of effort to smile when you’re around.",
                 "I’m not going to repeat myself, but I’m also glad to do anything that prevents you from talking.",
                 "Are all your friends this stupid as well? Maybe we can invite them over and, together, you’d constitute one working brain cell.",
                 "Break a leg. No, seriously, break a leg.",
                 "This is a lose-lose situation for me. I lose my valuable time and any semblance of compassion I had left.",
                 "If you ever cross my mind, I’ll make sure it’s a busy intersection.",
                 "It got a little chillier in here once I realized you were a cold-hearted bitch.",
                 "I have a present for you. I present to you: absolutely fucking nothing.",
                 "I’d tell you to blow your brains out, but I’m pretty certain there’s nothing there.",
                 "Are you normally this obnoxious, or is there some class you took?",
                 "Swallow your pride and your tongue while you’re at it.",
                 "I understand everything you said. I’m choosing to ignore you.",
                 "Your brain is working overtime today. You better pay it extra.",
                 "Glad I could be of assistance. Allow me to assist you in never walking again.",
                 "The series of mental backflips I had to do to try and understand your point should have broken my neck.",
                 "Don’t worry. Everyone makes mistakes. Your parents, for one.",
                 "Row, row, row your boat gently down a raging fucking waterfall.",
                 "Ditch the outfit. You’re enough of an asshat as it is.",
                 "I’d hate to come across a universe where you’re funny.",
                 "Good job. You almost reached a level of coherency resembling my newborn son.",
                 "I like you just the way you are: uninspiring, uninteresting, and dreadfully unfunny.",
                 "There was some terrible traffic accident on the news today. I was hoping that it was you.",
                 "The song “Army of One” is an ode to your loneliness.",
                 "I would like some tips on how to clear my mind from someone with nothing meaningful to contribute. Care to help?",
                 "Your absence would affect me greatly. I’d finally get some peace and quiet.",
                 "You’re the corner piece to an unsolvable puzzle: everyone looks right past you.",
                 "The hardest pill to swallow is knowing nothing is as lethal as your personality.",
                 "You’re like my fridge: always full of yourself yet offering an abundance of empty calories.",
                 "I didn’t think it was possible to give me more reasons to hate you until today.",
                 "You’re the type of person that uses their 3rd grade research paper as a resume booster.",
                 "I applaud your effort, but I think I’m the only one in the audience. And I’m leaving early.",
                 "Spontaneity is the spice of life, and you’re as plain as they come.",
                 "Every cloud has a silver lining. I’m still trying to figure out yours.",
                 "Large and in charge isn’t your excuse to be a fat asshole.",
                 "The fact that someone wakes up to your face in the morning should be alarming. And yes, I’m referring to the mirror as well.",
                 "“Spending some time” would imply I’d spend anything on your ungrateful ass.",
                 "A corpse is better company than you.",
                 "The Department of Homeland Security added your existence to the list of “Natural Disasters.”",
                 "You can be anything you want…except good looking.",
                 "Last week’s test was on shapes and colors, but it appears like you might have to revisit that after today’s conversation.",
                 "Is part 2 of your argument coming out soon or is that it?",
                 "The truth will set you free. You suck. Ok, you’re free to go.",
                 "The 0.01% of germs are afraid of contracting stupidity from you.",
                 "When they said grow a pair, they didn’t mean for you to have kids.",
                 "What did you want to be when you grew up? A pain in the ass?",
                 "Funny, I don’t remember you raising your hand. I’m going to call on someone else.",
                 "I’m surprised your teeth aren’t brown from all the shit talking you do.",
                 "You have a lot in common with the wart on my toe: You’re hard to get rid of, and I can’t stand the pain you bring me daily.",
                 "Being a dick to me won’t make yours bigger.",
                 "All mistakes are fixable, yet you aren’t.",
                 "Did I hurt your ego? Do you want a kissy on your boo-boo?",
                 "Usually my rule is “3 strikes and you’re out,” but you were out of my mind as soon as you started spewing your bullshit.",
                 "I gave out all my trophies a while ago, but here’s a participation award.",
                 "You’re the reason the divorce rate is so high.",
                 "You are so full of shit, the toilet’s jealous.",
                 "Don’t hate me because I’m beautiful. Hate me because your boyfriend thinks so.",
                 "I may love to shop but I will never buy your bull.",
                 "Do your parents even realize they’re living proof that two wrongs don’t make a right?",
                 "You’re about as useful as an ashtray on a motorcycle.",
                 "I love what you’ve done with your hair. How do you get it to come out of the nostrils like that?",
                 "Your kid is so annoying, he makes his Happy Meal cry.",
                 "The people who tolerate you on a daily basis are the real heroes.",
                 "Aww, it’s so cute when you try to talk about things you don’t understand.",
                 "I believed in evolution until I met you.",
                 "You’re my favorite person… besides every other person I’ve ever met.",
                 "I hope your wife brings a date to your funeral.",
                 "Feed your own ego. I’m busy.",
                 "Earth is full. Go home.",
                 "You are like a cloud. When you disappear it’s a beautiful day.",
                 "If your brain was dynamite, there wouldn’t be enough to blow your hat off.",
                 "Your family tree must be a cactus ‘cause you’re all a bunch of pricks.",
                 "What doesn’t kill you, disappoints me.",
                 "You see that door? I want you on the other side of it.",
                 "Don’t get bitter, just get better.",
                 "Keep rolling your eyes, you might eventually find a brain.",
                 "Were you born on the highway? That is where most accidents happen.",
                 "People like you are the reason God doesn’t talk to us anymore.",
                 "If you’re going to be two-faced, at least make one of them pretty.",
                 "If I threw a stick, you’d leave, right?",
                 "You’re not stupid! You just have bad luck when you’re thinking.",
                 "You should really come with a warning label.",
                 "Hey, your village called – they want their idiot back.",
                 "You are proof that evolution can go in reverse.",
                 "You’re about as useful as a screen door on a submarine.",
                 "Light travels faster than sound which is why you seemed bright until you spoke.",
                 "Take my lowest priority and put yourself beneath it.",
                 "I could eat a bowl of alphabet soup and poop out a smarter statement than whatever you just said.",
                 "If genius skips a generation, your children will be brilliant.",
                 "I’d slap you but I don’t want to make your face look any better.",
                 "You are the human version of period cramps.",
                 "Too bad you can’t Photoshop your ugly personality.",
                 "Where’d you get your clothes, girl, American Apparently Not?",
                 "You’re a grey sprinkle on a rainbow cupcake.",
                 "Don’t be ashamed of who you are. That’s your parent’s job.",
                 "Someday you’ll go far. I hope you stay there.",
                 "You’re impossible to underestimate.",
                 "I’d give you a nasty look but you’ve already got one.",
                 "Grab a straw, because you suck.",
                 "You’re like the end pieces of a loaf of bread. Everyone touches you, but nobody wants you.",
                 "You fear success, but you really have nothing to worry about.",
                 "If I wanted to hear from an asshole, I’d fart.",
                 "Somewhere out there, there’s a tree working very hard to produce oxygen so that you can breathe. I think you should go and apologize to it.",
                 "You are a pizza burn on the roof of the world’s mouth.",
                 "You look like something that came out of a slow cooker.",
                 "If laughter is the best medicine, your face must be curing the world.",
                 "If you were an inanimate object, you’d be a participation trophy.",
                 "I was hoping for a battle of wits but you appear to be unarmed.",
                 "Hey, you have something on your chin. No, the 3rd one down.",
                 "I’ll never forget the first time we met. But I’ll keep trying.",
                 "Child, I’ve forgotten more than you ever knew.",
                 "You’re the reason God created the middle finger.",
                 "I’m not insulting you, I’m describing you.",
                 "I will ignore you so hard you will start doubting your existence.",
                 "Hold still. I’m trying to imagine you with personality.",
                 "Your secrets are always safe with me. I never even listen when you tell me them.",
                 "If you’re going to act like a turd, go lay on the yard.",
                 "Good story, but in what chapter do you shut up?",
                 "You are more disappointing than an unsalted pretzel.",
                 "You look like a ‘before’ picture.",
                 "People like you are the reason I’m on medication.",
                 "Isn’t there a bullet somewhere you could be jumping in front of?",
                 "If ignorance is bliss, you must be the happiest person on the planet.",
                 "Please just tell me you don’t plan to home-school your kids.",
                 "Don’t you get tired of putting makeup on your two faces every morning?",
                 "I’ve been called worse by better.",
                 "Jesus might love you, but everyone else definitely thinks you’re an idiot.",
                 "Your ass must be pretty jealous of all the shit that comes out of your mouth.",
                 "You’ll never be the man your mom is.",
                 "I envy people who have never met you.",
                 "Your only purpose in life is to become an organ donor.",
                 "Don’t worry about me. Worry about your eyebrows.",
                 "It’s kind of hilarious watching you try to fit your entire vocabulary into one sentence.",
                 "There are some remarkably dumb people in this world. Thanks for helping me understand that.",
                 "I’ve seen people like you before, but I had to pay admission.",
                 "Were you born this stupid or did you take lessons?",
                 "You need a kiss on the neck from a crocodile.",
                 "You bring everyone so much joy when you leave the room.",
                 "Unless your name is Google, stop acting like you know everything!",
                 "Your face makes onions cry.",
                 "Have a nice day, somewhere else.",
                 "I don’t have the time or the crayons to explain this to you.",
                 "Remember when I asked for your opinion? Me neither.",
                 "May both sides of your pillow be uncomfortably warm.",
                 "I thought of you today. It reminded me to take out the trash.",
                 "I told my therapist about you.",
                 "Calling you an idiot would be an insult to all stupid people.",
                 "I am returning your nose. I found it in my business.",
                 "I don’t know what your problem is, but I’m guessing it’s hard to pronounce.",
                 "Who ate your bowl of sunshine this morning, thundercloud?",
                 "Jealousy is a disease. Get well soon.",
                 "Everyone’s entitled to act stupid once in a while, but you really abuse the privilege.",
                 "That sounds like a you problem.",
                 "Stupidity isn’t a crime, so you’re free to go.",
                 "I’m not saying I hate you, but I would unplug your life support to charge my phone.",
                 "And by ‘K.’ I meant ‘F*ck you!’",
                 "Life is full of disappointments, just ask your parents.",
                 "May your life be as pleasant as you are.",
                 "Awww...my middle finger likes you.",
                 "You’re giving me the douchebumps.",
                 "Your face is just fine, but you’ll have to put a bag over that personality.",
                 "Why is it acceptable for you to be an idiot but not for me to point it out?",
                 "I would love to insult you, but that would be beyond the level of your intelligence.",
                 "I have seen bread smarter than you.",
                 "Awww...it’s cute when you try to talk about things you don’t understand.",
                 "You need a kiss...on the neck...from a crocodile.",
                 "I hear there’s a new app called “Sense of Humor.” Please download it.",
                 "ABRACADABRA! Nope, you’re still a b*tch.",
                 "Your ass must be jealous of all the sh*t that’s coming out of your mouth.",
                 "I hope you lose weight so there will be less of you!",
                 "Anyone who ever said they loved you lied.",
                 "I’m sorry for hurting your feelings, I thought you already knew you were stupid.",
                 "You’re giving me the silent treatment? Finally!",
                 "I’m sorry, you’ve mistaken me for someone who gives a damn.",
                 "Feed your own ego. I’m busy.",
                 "I would roast you but my mom told me that I'm not allowed to burn trash.",
                 "I’m so jealous of all the people that haven’t met you yet.",
                 "Whoever told you to be yourself simply couldn’t have given you worse advice.",
                 "I’ll try being nicer if you try being smarter.",
                 "Ever since I saw you in your family tree, I've wanted to cut it down.",
                 "Normally, people live and learn. You, on the other hand, just live.",
                 "They say: “You are what you eat.” How much crap did you eat this morning?",
                 "There’s no need to repeat yourself. I ignored you the first time.",
                 "I don’t argue with idiots. They will just lower me to their level, then beat me with experience.",
                 "If I had a dollar for every brain you don’t have, I’d have a dollar.",
                 "Whenever I see you, middle finger gets an erection.",
                 "I don't have an attitude problem. You have a perception problem!",
                 "You see that door? I want you on the other side of it.",
                 "It’s such a beautiful day to leave me alone. Scram!",
                 "You deserve a hug...around the neck...with a rope.",
                 "You aren’t worth the dust that the wind is blowing on your face.",
                 "Somewhere out there, there's a tree working very hard to produce oxygen so that you can breathe. I think you should go and apologize to it.",
                 "I love the sound you make when you shut up.",
                 "If I wanted to hear from an asshole, I would have farted.",
                 "Okay, let me file what you just said under ‘I couldn’t care less.’",
                 "I’ve been called worse by better people.",
                 "If I agreed with you, we’d both be wrong.",
                 "Know your role, shut your hole!",
                 "Someday, you'll look back on this, laugh nervously, and change the subject.",
                 "Too bad you can’t photoshop an ugly personality.",
                 "I’m sorry, was that meant to offend me? The only thing offending me right now though is your face.",
                 "I’m not rude. I just speak what everyone else is thinking of you.",
                 "I'd make a joke about your mother, but you being here has already done that for me.",
                 "Life’s a b*tch. Oh no, wait. That’s you.",
                 "Are you naturally this dumb or do you have to put in effort?",
                 "If I wanted to talk to you, I would have called you first.",
                 "The trash gets picked up early tomorrow. Be ready.",
                 "I don’t remember asking for your opinion.",
                 "You’re the reason nobody likes you.",
                 "‘Pew! Pew! Pew!’ That’s the sound of me deflecting your whiny b*tching with my happiness shield.",
                 "You consistently set low expectations and fail to achieve them.",
                 "Some people bring joy wherever they go. You, on the other hand, bring joy whenever you go.",
                 "Sometimes, I wish I was deaf so your grammar wouldn’t bother me so much.",
                 "I would like to leave you with one thought, but I’m not sure if you have anywhere to store it in.",
                 "Remember when I asked for your opinion? Yeah, me neither.",
                 "Shock me, say something intelligent.",
                 "Sometimes, it’s better to keep your mouth shut and give the impression that you’re stupid rather than open it and remove all doubt.",
                 "I’d slap you, but that would be animal abuse.",
                 "I thought of you today, and it pissed me off.",
                 "Isn’t this a battle of wits? You appear to be unarmed.",
                 "I see you've set aside this special time to humiliate yourself in public.",
                 "You couldn’t handle me even if I came with instructions.",
                 "On your mark, get set, go f*ck yourself!",
                 "You are validating my inherent mistrust of strangers.",
                 "The last time I saw something like you, I flushed it.",
                 "My life may be a joke, but it’s not as funny as your face.",
                 "Now I know why everyone talks about you behind your back.",
                 "If what you don't know can't hurt you, you're invulnerable.",
                 "If you’re gonna be a smartass, first you have to be smart. Otherwise, you’re just an ass.",
                 "Shit happens. I mean, look at your face.",
                 "You should introduce your upper lip to your lower lip sometime and shut up!",
                 "I wanna give you a high five...on the face...with a hammer.",
                 "If you’re going to wait for me to care, I hope you brought something to eat—because it’s probably going to take you a really long time.",
                 "Seriously, your mouth is so foul! Should I offer you a tic-tac or a toilet paper?",
                 "You must think you’re strong, but you only smell strong.",
                 "What you lack in intelligence, you more than make up for in stupidity.",
                 "I’d give you a nasty look, but I see you've already got one.",
                 "Did you fall from heaven? Because so did Satan!",
                 "Don't feel bad. A lot of people have no talent.",
                 "Keep talking. Who knows, someday you might be able to say something intelligent.",
                 "I may not be perfect, but at least I’m not you.",
                 "You’re like the end pieces of a loaf of bread. Everyone touches you, but nobody wants you.",
                 "Hey, I found your nose. It was in my business.",
                 "I’d insult you, but then I’d have to explain it afterwards, so never mind.",
                 "I’m not bossy. I just know what you should be doing.",
                 "You fear success, but you really have nothing to worry about.",
                 "You are like the sun—not because you light up my world, but because it hurts to look at you.",
                 "You look like something that came out of a slow cooker.",
                 "If laughter is the best medicine, your face must be curing the world.",
                 "I hope your day becomes filled with people like you.",
                 "If I had a dollar for every time you said something smart, I'd be broke.",
                 "You’re not pretty enough to be that stupid.",
                 "Brains aren't everything. In your case, they're nothing.",
                 "How do you keep yourself from not choking on the constant flow of bullsh*t that’s coming out of your mouth? You are seriously amazing!",
                 "If stupid could fly, you’d be a jet.",
                 "Keep talking...I’m diagnosing you.",
                 "I don’t understand your specific kind of ‘stupidity,’ but I do admire your total commitment to it.",
                 "Are you always so stupid or is today a special occasion?",
                 "I tried to put myself in your shoes, but they were cheap and ugly just like you.",
                 "You smell like drama and headache. Please stay away from me!",
                 "Can you die of constipation? I ask because I’m worried about how full of sh*t you are.",
                 "Life is full of disappointments, and I just added you to the list.",
                 "I can tell when you’re lying. Your lips are moving.",
                 "May the chocolate chips in your cookies always turn out to be raisins.",
                 "Were you born this stupid, or did you take lessons?",
                 "Of all the mistakes in the world, you are the mistakiest!",
                 "I will ignore you so hard you will start doubting your existence.",
                 "Before you tell me what I did wrong, you should first know that I don’t care.",
                 "If you’re going to act like a turd, go lay on the yard.",
                 "I get so emotional when you’re not around. The emotion is happiness, by the way.",
                 "I expected an intellectual conversation, but it seems there’s no one around to have that with.",
                 "Just because I’m smiling doesn’t mean I don’t want to hit you in the face.",
                 "You are not as bad as people say. You are much, MUCH worse!",
                 "I'm already visualizing the duct tape over your mouth.",
                 "I would slap you but sh*t splatters, and that would be too much of a mess.",
                 "How long did it take you to come up with that one?",
                 "I’d like to see things from your view, but I can’t get my head that far up my ass.",
                 "I bet your brain feels as good as new, seeing that you’ve never used it.",
                 "I’ve met several pricks before, but you sir are a cactus.",
                 "You look like a ‘before’ picture.",
                 "There’s someone for everyone, and the person for you is a psychiatrist.",
                 "Let's go to the zoo. I've always wanted to meet your family.",
                 "You shouldn’t act hard-to-get when you’re already hard-to-like.",
                 "Here, let me wash the stupid right off of you. Oh wait, it’s not coming off.",
                 "You speak an infinite deal of nothing.",
                 "It’s okay if you don’t like me. Not everyone has good taste.",
                 "Your brain has two parts—the 'left' and the 'right'. On the left side, there's nothing right. On the right side, there's nothing left.",
                 "It must be hard putting makeup on your two faces.",
                 "I didn’t know that answering a question was considered ‘talking back.’",
                 "If you don't like my opinion of you—improve yourself!",
                 "Whenever we hang out, I remember that God really does have a sense of humor.",
                 "If you ran like your mouth, you’d be in good shape.",
                 "I would ask you how old you are, but I know that you can't count that high.",
                 "2 words, 1 finger. Do the math!",
                 "You are so ugly that when you looked in the mirror, your reflection walked away.",
                 "There’s only one thing that keeps me from breaking you in half—I don’t want two of you around!",
                 "Even dogs don’t like you.",
                 "Jealousy is a disease. Get well soon!",
                 "If ignorance is bliss, you must be the happiest person on the planet.",
                 "If you spoke your mind, you’d be speechless.",
                 "I heard your parents took you to a dog show and you won.",
                 "Sorry for the mean, awful accurate things I said.",
                 "Maybe you should eat some makeup so you can be pretty on the inside too.",
                 "Are you afraid that zombies will eat your brain? Nah, you’ll be fine.",
                 "If everyone was like you, the human race would lose faith in the world.",
                 "When your mom dropped you off at school, she got apprehended by the authorities for littering.",
                 "I can explain it to you, but I can’t understand it for you.",
                 "Since narcissistic is such a big word for you, how about asshole? You know what an asshole is, right?",
                 "I’m sorry you got offended that one time you were treated the exact way you treat everyone all the time.",
                 "Me, jealous of you? Bless your delusional heart!",
                 "Oops, my bad. I could’ve sworn I was dealing with an adult.",
                 "If I were a bird, you’d be the first person I’d poop on.",
                 "Stupidity is not a crime, so you’re free to go.",
                 "I have neither the time nor the crayons to explain this to you.",
                 "I wasn’t born with enough middle fingers to let you know how I feel.",
                 "Please cancel my subscription to your issues.",
                 "Oh, I’m sorry. I didn’t realize my happiness makes you so miserable.",
                 "If you really want to know about mistakes, you should ask your parents.",
                 "The only thing I don’t like about you is that constant inhaling and exhaling habit you have.",
                 "Mind if I ask where the OFF button for your mouth is?",
                 "Here’s a tissue, you have a little piece of sh*t on your lips.",
                 "I hope you step on a LEGO.",
                 "I’m sorry I didn’t get that. I don’t speak bullsh*t.",
                 "It’s okay if you disagree with me. I can’t force you to be right.",
                 "I may be fat, but fat can be burned. Ugly, on the other hand, is much more difficult to fix.",
                 "If I wanted a b*tch, I would have purchased a dog.",
                 "Unless your name is Google, stop acting like you know everything!",
                 "You know what’s funny? Not you, so shut up!",
                 "I’d like to help you out. Which way did you come in?",
                 "Long story short, because you wouldn’t be able to follow with the long one.",
                 "Goeth & fucketh thyself!",
                 "Beauty is skin deep, but ugly is to the bone.",
                 "May you always step on a wet spot after putting on fresh socks.",
                 "May both sides of your pillow be uncomfortably warm.",
                 "There's only one problem with your face, I can see it.",
                 "I told my therapist about you.",
                 "Did your parents ever ask you to run away?",
                 "So if I typed ‘idiot’ into Google image search, would your picture come up?",
                 "I don’t know what your problem is, but I’m guessing it’s hard to pronounce.",
                 "I’d love to kill you with kindness, but all I have is this chainsaw.",
                 "Who ate your bowl of sunshine this morning, thundercloud?",
                 "I’m not arguing. I’m simply explaining why I’m right.",
                 "You have the right to remain silent because whatever you say will probably be stupid anyway.",
                 "Don't you love nature despite what it did to you?",
                 "I’m not insulting you. I’m describing you.",
                 "Calling you an idiot would be an insult to all stupid people in the world.",
                 "I’m busy, you’re ugly. Have a nice day.",
                 "I don’t know what makes you so stupid, but it really works.",
                 "Look at the time, it’s time for you to shut the f*ck up!",
                 "You are about to exceed the limits of my medication.",
                 "I can only please one person a day. Today isn’t your day. Tomorrow isn’t looking good either.",
                 "My alone time is meant for your safety.",
                 "I desire that we be better strangers.",
                 "In order to insult me, I must first value your opinion. Nice try though."
 ]
